---
- name: 0. 앤서블 도커 제어용 파이썬 라이브러리 설치
  ansible.builtin.apt:
    name: 
      - python3-docker
      - python3-requests
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: 1. 데이터 영속성을 위한 호스트 볼륨 디렉터리 생성
  ansible.builtin.file:
    path: "{{ db_host_volume_path }}"
    state: directory
    mode: '0700'
    owner: '999'
    group: '999'

- name: 2. PostgreSQL 도커 이미지 미리 Pull
  community.docker.docker_image:
    name: "postgres"
    tag: "{{ db_version }}"
    source: pull
    force_source: false

- name: 3. PostgreSQL 컨테이너 설정 및 구동
  # 클라우드 보안 그룹에서 5432 포트 접근을 허용해야 통신이 가능합니다.
  community.docker.docker_container:
    name: "{{ db_container_name }}"
    image: "postgres:{{ db_version }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ ansible_default_ipv4.address }}:5432:5432"
    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db_name }}"
    volumes:
      - "{{ db_host_volume_path }}:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U '{{ db_user }}' -d '{{ db_name }}'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    comparisons:
      env: strict
      volumes: strict