all:
  children:
    web_servers:
      hosts:
        ykk_web:
          ansible_host: 3.34.194.142
          ansible_user: ykk-admin
    was_servers:
      hosts:
        ykk_was:
          ansible_host: 13.125.126.117
          ansible_user: ykk-admin
    db_servers:
      hosts:
        ykk_db:
          ansible_host: 13.125.236.222
          ansible_user: ykk-admin