---
# =================================================================
# DB 컨테이너 구동을 위한 환경 변수 및 설정 정의
# =================================================================
db_container_name: "ykk-postgres-db"
db_version: "16-alpine"  # 경량화 및 보안 강화를 위한 Alpine 이미지 사용

# PostgreSQL 접속 정보 (보안 변수)
db_user: "ykk_admin"
db_password: "1234qwer"
db_name: "ykk_db"

# 호스트와 동기화할 데이터 저장소 경로
db_host_volume_path: "/var/lib/ykk/postgres/data"