#~/ansible/roles/db/tasks/main.yml
---
- name: 기존 시스템 서비스 기반 모니터링 에이전트 중지
  ansible.builtin.systemd:
    name: node_exporter
    state: stopped
    enabled: no
  ignore_errors: yes

- name: 서버 내부에 프로젝트 디렉터리 구조 생성
  ansible.builtin.file:
    path: /opt/project/docker/compose/db
    state: directory
    mode: '0755'

- name: 운영 환경용 도커 컴포즈 명세서 전송
  ansible.builtin.template:
    src: ~/project/docker/compose/db/prod.yml.j2
    dest: /opt/project/docker/compose/db/prod.yml

- name: 도커 컴포즈를 이용한 데이터베이스 세트 가동
  community.docker.docker_compose_v2:
    project_src: /opt/project/docker/compose/db
    files:
      - prod.yml
    state: present
    build: always